name: speech_to_text
description: A Flutter plugin that exposes speech-to-text recognition on Android, iOS, and Web.
version: 5.6.0
homepage: https://github.com/csdcorp/speech_to_text

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  speech_to_text_platform_interface: ^2.0.1
  json_annotation: ^4.0.1
  clock: ^1.1.0
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  json_serializable: ^4.0.2
  mockito: ^5.0.0
  plugin_platform_interface: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.csdcorp.speech_to_text
        pluginClass: SpeechToTextPlugin
      ios:
        pluginClass: SpeechToTextPlugin
      web:
        pluginClass: SpeechToTextPlugin
        fileName: speech_to_text_web.dart